package com.hampcoders.electrolink.analytics.interfaces.rest.resources;

/**
 * Resource class representing the revenue generated by a technician
 * for a specific period, including total revenue,
 * the count of services performed, and the average revenue per service.
 *
 * @param technicianId the ID of the technician
 * @param period the period for which the revenue is calculated
 * @param totalRevenue the total revenue generated by the technician during the period
 * @param servicesCount the total number of services performed by the technician during the period
 * @param averageRevenuePerService the average revenue generated per service performed
 *     by the technician during the period
 */
public record TechnicianRevenueResource(
    Long technicianId,
    String period,
    double totalRevenue,
    int servicesCount,
    double averageRevenuePerService
) {
}
