services:
  - type: web
    name: electrolink-backend-api
    runtime: docker
    region: oregon
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: electrolink-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: electrolink-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: electrolink-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: electrolink-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: electrolink-db
          property: password

databases:
  - name: electrolink-db
    databaseName: electrolink_spring_pruebas
    plan: free
    region: oregon