services:
  # Web Service - Usando la imagen Docker de Electrolink
  - type: web
    name: electrolink-backend-api
    env: docker
    region: oregon
    plan: free
    dockerImagePath: legendnt/electrolink-backend-api:latest
    envVars:
      - key: PORT
        value: "8091"

      # Mapeo automatizado desde la base de datos administrada de Render
      - key: DB_HOST
        fromDatabase:
          name: electrolink-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: electrolink-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: electrolink-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: electrolink-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: electrolink-db
          property: password

      # Variables obligatorias adicionales
      - key: CLOUDINARY_CLOUD_NAME
        value: ""
      - key: CLOUDINARY_API_KEY
        value: ""
      - key: CLOUDINARY_API_SECRET
        value: ""

    healthCheckPath: /actuator/health

databases:
  # Base de Datos PostgreSQL gestionada por Render
  - name: electrolink-db
    databaseName: electrolink_spring_pruebas
    plan: free
    region: oregon