package com.hampcoders.electrolink.analytics.interfaces.rest.transform;

import com.hampcoders.electrolink.analytics.interfaces.rest.resources.HomeOwnerConsumptionResource;
import com.hampcoders.electrolink.analytics.interfaces.rest.resources.TechnicianPerformanceResource;
import com.hampcoders.electrolink.analytics.interfaces.rest.resources.TechnicianRevenueResource;
import java.util.List;

/**
 * Assembler to convert analytics data into REST resources for the Analytics API.
 */
public class AnalyticsResourceFromEntityAssembler {

  /**
   * Converts a list of HomeOwnerConsumptionResource objects into a list of
   *     HomeOwnerConsumptionResource objects.
   *
   * @param resources the resource of {@link HomeOwnerConsumptionResource}
   * @return a list of {@link HomeOwnerConsumptionResource}
   */
  public static List<HomeOwnerConsumptionResource> toHomeOwnerConsumptionResourceList(
      List<HomeOwnerConsumptionResource> resources) {
    return resources;
  }

  /**
   * Converts the given parameters into a TechnicianPerformanceResource object.
   *
   * @param technicianId the ID of the technician
   * @param totalServicesCompleted the total number of services completed by the technician
   * @param averageRating the average rating received by the technician from customers
   * @param averageCompletionTimeHours the average time taken by the technician
   *     to complete a service, in hours
   * @param pendingServices the number of services that are currently pending for the technician
   * @return a {@link TechnicianPerformanceResource}
   */
  public static TechnicianPerformanceResource toTechnicianPerformanceResource(
      Long technicianId, int totalServicesCompleted, double averageRating,
      double averageCompletionTimeHours, int pendingServices) {
    return new TechnicianPerformanceResource(technicianId, totalServicesCompleted,
        averageRating, averageCompletionTimeHours, pendingServices);
  }

  /**
   * Converts the given parameters into a TechnicianRevenueResource object.
   *
   * @param technicianId the ID of the technician
   * @param period the period for which to calculate revenue
   * @param totalRevenue the total revenue generated by the technician
   * @param servicesCount the number of services completed by the technician
   * @param averageRevenuePerService the average revenue generated per service
   * @return a {@link TechnicianRevenueResource}
   */
  public static TechnicianRevenueResource toTechnicianRevenueResource(
      Long technicianId, String period, double totalRevenue,
      int servicesCount, double averageRevenuePerService) {
    return new TechnicianRevenueResource(technicianId, period, totalRevenue,
        servicesCount, averageRevenuePerService);
  }
}
