spring.application.name=electrolink-platform

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:electrolink_spring_pruebas}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
server.port=${PORT:8091}

#spring.datasource.url=jdbc:postgresql://db.pssdjocoyfbmhitsajou.supabase.co:5432/postgres?sslmode=require
#spring.datasource.username=postgres
#spring.datasource.password=aNdi3hEVwjyIIlJT
#server.port=8080

spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=10

# Spring Data JPA Configuration
spring.jpa.database=postgresql
spring.jpa.show-sql=true

# Spring Data JPA Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=com.hampcoders.electrolink.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

# Exponer los endpoints de Actuator (especialmente el de prometheus)
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

# Application Information for Documentation
documentation.application.description=@project.description@
documentation.application.version=@project.version@

# Photo Storage Provider Configuration
monitoring.photos.storage.provider=local

# Cloudinary Configuration (used when provider=cloudinary)
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dm6cfpwvi}
cloudinary.api-key=${CLOUDINARY_API_KEY:231188718817798}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:J1hpZ9nTmlOBiLvxlDcDu8wzFmA}

# JWT Configuration Properties
authorization.jwt.secret=WriteHereYourSecretStringForTokenSigningCredentials
authorization.jwt.expiration.days=10
