package com.hampcoders.electrolink.analytics.domain.model.queries;

/**
 * Query object representing the data needed to retrieve the revenue generated by a technician.
 *
 * @param technicianId The ID of the technician whose revenue is being queried.
 * @param months The number of months for which to retrieve the revenue data.
 */
public record GetTechnicianRevenueQuery(Long technicianId, int months) {
}
